module.exports = {
    news: [
        { name: 'title', type: 'text', required: true },
        { name: 'content', type: 'textarea', required: true },
        { name: 'photo', type: 'file', required: false },
        { name: 'video', type: 'file', required: false },
    ],
    branch: [
        { name: 'branchName', type: 'text', required: true },
        { name: 'address', type: 'text', required: true },
        { name: 'phone', type: 'text', required: true },
        { name: 'email', type: 'email', required: false },
        { name: 'location', type: 'text', required: false },
        { name: 'photo', type: 'file', required: false },
    ],
    staff: [
        { name: 'Employeename', type: 'text', required: true },
        { name: 'position', type: 'text', required: true },
        { name: 'email', type: 'email', required: false },
        { name: 'phone', type: 'text', required: false },
        { name: 'role', type: 'text', required: true },
        {name: 'bio', type: 'textarea', required: false},
        { name: 'TshirtNo', type: 'text', required: false },
        { name: 'photo', type: 'file', required: false },
        { name: 'joinedAt', type: 'date', required: false },
    ],
    story: [
        { name: 'title', type: 'text', required: true },
        { name: 'year', type: 'number', required: true },
        { name: 'content', type: 'textarea', required: true },
        { name: 'photo', type: 'file', required: false },
    ],
    service: [
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea', required: true },
        { name: 'photo', type: 'file', required: false },
        { name: 'location', type: 'text', required: true },
        { name: 'birthRangeFrom', type: 'number', required: true },
        { name: 'birthRangeTo', type: 'number', required: true },
        { name: 'sport', type: 'select', options: ['football', 'basketball'], required: true },
        { name: 'trainingDays', type: 'checkbox', options: ['Fri','Sat','Sun','Mon','Tue','Wed','Thu'], required: true },
        { name: 'trainingTimeFrom', type: 'time', required: true },
        { name: 'trainingTimeTo', type: 'time', required: true },
        { name: 'oneMonth', type: 'text', default: '30 KD', required: false },
        { name: 'threeMonth', type: 'text', default: '90 KD', required: false },
        { name: 'brothers', type: 'text', default: '30 KD', required: false },
    ],
    album: [
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea', required: true },
    ],
};
