module.exports = {
    news: [
        { name: 'title_ar', type: 'text', required: true },
        { name: 'title_en', type: 'text', required: false },
        { name: 'content_ar', type: 'textarea', required: true },
        { name: 'content_en', type: 'textarea', required: false },
        { name: 'photo', type: 'file', required: false },
        { name: 'video', type: 'file', required: false },

    ],
    branch: [
        { name: 'branchName_ar', type: 'text', required: true },
        { name: 'branchName_en', type: 'text', required: false },
        { name: 'address_ar', type: 'text', required: true },
        { name: 'address_en', type: 'text', required: false },
        { name: 'phone', type: 'text', required: true },
        { name: 'email', type: 'email', required: false },
        { name: 'location', type: 'text', required: false },
        { name: 'photo', type: 'file', required: false },

    ],
    staff: [
        { name: 'Employeename_ar', type: 'text', required: true },
        { name: 'Employeename_en', type: 'text', required: false },
        { name: 'position_ar', type: 'text', required: true },
        { name: 'position_en', type: 'text', required: false },
        { name: 'role_ar', type: 'text', required: true },
        { name: 'role_en', type: 'text', required: false },
        { name: 'bio_ar', type: 'textarea', required: false },
        { name: 'bio_en', type: 'textarea', required: false },
        { name: 'email', type: 'email', required: false },
        { name: 'phone', type: 'text', required: false },
        { name: 'TshirtNo', type: 'text', required: false },
        { name: 'photo', type: 'file', required: false },
        { name: 'joinedAt', type: 'date', required: false },
    ],
    story: [
        { name: 'title_ar', type: 'text', required: true },
        { name: 'title_en', type: 'text', required: false },
        { name: 'content_ar', type: 'textarea', required: false },
        { name: 'content_en', type: 'textarea', required: false },
        { name: 'year', type: 'number', required: true },
        { name: 'photo', type: 'file', required: false },

    ],
    service: [
        { name: 'title_ar', type: 'text', required: true },
        { name: 'title_en', type: 'text', required: false },
        { name: 'description_ar', type: 'textarea', required: true },
        { name: 'description_en', type: 'textarea', required: false },
        { name: 'photo', type: 'file', required: false },
        { name: 'location_ar', type: 'text', required: true },
        { name: 'location_en', type: 'text', required: false },
        { name: 'birthRangeFrom', type: 'number', required: true },
        { name: 'birthRangeTo', type: 'number', required: true },
        { name: 'sport_ar', type: 'select', options: ['football', 'basketball'], required: true },
        { name: 'sport_en', type: 'select', options: ['football', 'basketball'], required: false },
        { name: 'trainingDays', type: 'checkbox', options: ['Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu'], required: true },
        { name: 'trainingTimeFrom', type: 'time', required: true },
        { name: 'trainingTimeTo', type: 'time', required: true },
        { name: 'oneMonth', type: 'text', default: '30 KD', required: false },
        { name: 'threeMonth', type: 'text', default: '90 KD', required: false },
        { name: 'brothers', type: 'text', default: '30 KD', required: false },
    ],
    album: [
        { name: 'title_ar', type: 'text', required: true },
        { name: 'title_en', type: 'text', required: false },
        { name: 'description_ar', type: 'textarea', required: true },
        { name: 'description_en', type: 'textarea', required: false },
        

    ],
};
